# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(
                default=False,
                help_text='Superadmins can manage other admin accounts and restore the database. '
                           'Regular admins (operators) cannot.',
            ),
        ),
    ]
