# Generated by Django 5.2.17 on 2026-08-30 07:05

from django.db import migrations, models


def normalize_and_dedupe_emails(apps, schema_editor):
    """Lowercase emails, map '' to NULL, and break any duplicate-email groups.

    Runs BEFORE the unique index is applied so existing rows can never make
    the migration fail. Duplicates (kept: lowest id) are non-destructively
    cleared to NULL on the losing accounts rather than deleting them.
    """
    User = apps.get_model('auth_app', 'User')
    seen = {}
    for user in User.objects.order_by('id').iterator():
        raw = (user.email or '').strip()
        if not raw:
            # Old schema stored blank as '' (NOT NULL); the column is now
            # nullable so '' can collapse to NULL and never hit the unique
            # index (two accounts with '' would otherwise collide).
            user.email = None
            user.save(update_fields=['email'])
            continue
        normalized = raw.lower()
        if normalized in seen:
            user.email = None
            user.save(update_fields=['email'])
            continue
        seen[normalized] = user.id
        if user.email != normalized:
            user.email = normalized
            user.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Stored lowercased; unique across all users.', max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.RunPython(
            normalize_and_dedupe_emails,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Stored lowercased; unique across all users.', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]