# Generated by Django 6.0.4 on 2026-05-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='waste_photos/'),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='photo_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='photo_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
