# Generated by Django 6.0.4 on 2026-05-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bin',
            new_name='bins_status_f43009_idx',
            old_name='bins_status_type_idx',
        ),
        migrations.RenameIndex(
            model_name='bin',
            new_name='bins_status_f193e5_idx',
            old_name='bins_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='bin',
            new_name='bins_waste_t_5ca511_idx',
            old_name='bins_waste_type_idx',
        ),
        migrations.RenameIndex(
            model_name='driver',
            new_name='drivers_is_avai_fc6fa0_idx',
            old_name='drivers_available_vehicle_idx',
        ),
        migrations.RenameIndex(
            model_name='driver',
            new_name='drivers_is_avai_6477b9_idx',
            old_name='drivers_available_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_a4dd5c_idx',
            old_name='notifs_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_611c58_idx',
            old_name='notifs_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_is_read_595d11_idx',
            old_name='notifs_read_created_idx',
        ),
        migrations.RenameIndex(
            model_name='route',
            new_name='routes_driver__a8fbb9_idx',
            old_name='routes_driver_status_idx',
        ),
        migrations.RenameIndex(
            model_name='route',
            new_name='routes_vehicle_11aca2_idx',
            old_name='routes_vehicle_status_idx',
        ),
        migrations.RenameIndex(
            model_name='route',
            new_name='routes_status_fead7c_idx',
            old_name='routes_status_planned_idx',
        ),
        migrations.RenameIndex(
            model_name='schedule',
            new_name='schedules_driver__900ce8_idx',
            old_name='schedules_driver_active_idx',
        ),
        migrations.RenameIndex(
            model_name='schedule',
            new_name='schedules_vehicle_1996bc_idx',
            old_name='schedules_vehicle_active_idx',
        ),
        migrations.RenameIndex(
            model_name='schedule',
            new_name='schedules_is_acti_095b69_idx',
            old_name='schedules_active_zone_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='vehicles_status_4cdff1_idx',
            old_name='vehicles_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='vehicles_vehicle_7251c0_idx',
            old_name='vehicles_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='wasterequest',
            new_name='waste_reque_status_7d48a7_idx',
            old_name='requests_status_scheduled_idx',
        ),
        migrations.RenameIndex(
            model_name='wasterequest',
            new_name='waste_reque_user_id_3a032f_idx',
            old_name='requests_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='wasterequest',
            new_name='waste_reque_driver__d7b998_idx',
            old_name='requests_driver_status_idx',
        ),
        migrations.RenameIndex(
            model_name='wasterequest',
            new_name='waste_reque_status_c5ca20_idx',
            old_name='requests_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='wasterequest',
            new_name='waste_reque_created_68cc19_idx',
            old_name='requests_created_idx',
        ),
    ]
