# Generated by Django 6.0.4 on 2026-07-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
