# Generated by Django 6.0.4 on 2026-07-14 07:34

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_wasterequest_deleted_at_wasterequest_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('missed_pickup', 'Missed Pickup'), ('driver_behavior', 'Driver Behavior'), ('illegal_dumping', 'Illegal Dumping'), ('overflowing_bin', 'Overflowing Bin'), ('app_issue', 'App Issue'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, help_text='Accepted formats: JPG, JPEG, PNG, GIF, WebP (Max 5MB)', null=True, upload_to='complaint_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', '-created_at'], name='complaints_status_dbbea4_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['complaint_type'], name='complaints_complai_9a684f_idx'),
        ),
    ]
