# Generated by Django 6.0.4 on 2026-07-17 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0012_wasterequestphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterequest',
            name='photo_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='photo_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='wasterequestphoto',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='wasterequestphoto',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
