# Generated by Django 6.0.4 on 2026-07-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0015_wasterequest_submitting_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='ml_confidence',
            field=models.FloatField(blank=True, help_text='ML model confidence percentage (0-100) for the severity prediction.', null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='needs_manual_review',
            field=models.BooleanField(default=False, help_text='True if ML confidence was below the review threshold — admin should verify manually.'),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Auto-detected waste severity from the gatekeeper ML model.', max_length=10, null=True),
        ),
    ]
