# Generated by Django 6.0.4 on 2026-07-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0016_wasterequest_ml_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='guest_token',
            field=models.CharField(blank=True, db_index=True, help_text='Random token set client-side when a guest (not logged in) submits a request, so it can later be claimed/linked to their account once they register or log in.', max_length=64, null=True),
        ),
    ]
