# Generated by Django 6.0.4 on 2026-07-27 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0017_wasterequest_guest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='completion_distance_meters',
            field=models.FloatField(blank=True, help_text="Distance (meters) between driver's completion GPS and the reported pickup location.", null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='completion_flagged',
            field=models.BooleanField(db_index=True, default=False, help_text='True if driver completed >500m away from pickup location — needs admin review.'),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='completion_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Driver's GPS location captured when marking this request completed.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='completion_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
