# Generated by Django 6.0.4 on 2026-07-27 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0019_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_document',
            field=models.FileField(blank=True, help_text='Driving license document (PDF only, max 5MB)', null=True, upload_to='driver_licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
