# Generated by Django 6.0.4 on 2026-07-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0018_wasterequest_completion_distance_meters_and_more'),
        ('api_app', '0020_driver_license_document'),
    ]

    operations = [
    ]
