# Generated by Django 6.0.4 on 2026-07-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0021_merge_20260727_1622'),
        ('api_app', '0021_merge_20260728_1635'),
    ]

    operations = [
    ]
