# Generated by Django 6.0.4 on 2026-08-03 06:45

import django.core.validators
from django.db import migrations, models

import api_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0022_merge_20260728_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, help_text='Accepted formats: JPG, JPEG, PNG, GIF, WebP (Max 5MB)', null=True, upload_to='complaint_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), api_app.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_document',
            field=models.FileField(blank=True, help_text='Driving license document (PDF only, max 5MB)', null=True, upload_to='driver_licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), api_app.validators.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='wasterequest',
            name='photo',
            field=models.ImageField(blank=True, help_text='Accepted formats: JPG, JPEG, PNG, GIF, WebP (Max 5MB)', null=True, upload_to='waste_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), api_app.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='wasterequestphoto',
            name='photo',
            field=models.ImageField(upload_to='waste_photos/extra/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), api_app.validators.validate_image_file]),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'planned')), fields=('driver', 'planned_date', 'status'), name='unique_planned_route_per_driver_per_day'),
        ),
    ]
