# Generated by Django 6.0.4 on 2026-08-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0023_alter_complaint_photo_alter_driver_license_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Optional email a guest can provide at submission time. Used to send a claim link as a backup in case the browser-stored guest_token (localStorage) is lost — e.g. cleared browser data or switching devices before registering.', max_length=254, null=True),
        ),
    ]