# Generated by Django 6.0.4 on 2026-08-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0024_add_guest_email_to_wasterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasterequest',
            name='guest_email',
        ),
    ]
