# Generated by Django 6.0.4 on 2026-08-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0025_remove_wasterequest_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='guest_email',
            field=models.EmailField(blank=True, db_index=True, help_text='Optional email a guest provides at submission time. It is a backup claim channel: if the browser-stored guest_token is lost (cleared browser data, switched devices), registering or logging in with this email automatically links these requests to that account.', max_length=254, null=True),
        ),
    ]
