# Generated by Django 6.0.4 on 2026-09-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0027_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='zone',
            field=models.CharField(choices=[('north', 'North Zone'), ('south', 'South Zone'), ('east', 'East Zone'), ('west', 'West Zone'), ('central', 'Central Zone')], db_index=True, default='central', max_length=20),
        ),
    ]
