# Generated by Django 5.2.17 on 2026-09-02 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0027_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverBreakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('lunch', 'Lunch'), ('fuel', 'Fuel'), ('rest', 'Rest'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'driver_break_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='break_reason',
            field=models.CharField(blank=True, help_text='Optional reason for the current break (lunch, fuel, rest, other).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='break_started_at',
            field=models.DateTimeField(blank=True, help_text='When the current break session started.', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='on_break',
            field=models.BooleanField(default=False, help_text='True while the driver has marked themselves on a break.'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_available', 'on_break'], name='drivers_is_avai_210358_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['on_break', '-break_started_at'], name='drivers_on_brea_db5cc1_idx'),
        ),
        migrations.AddField(
            model_name='driverbreaklog',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_logs', to='api_app.driver'),
        ),
        migrations.AddIndex(
            model_name='driverbreaklog',
            index=models.Index(fields=['driver', '-started_at'], name='driver_brea_driver__1e245e_idx'),
        ),
        migrations.AddIndex(
            model_name='driverbreaklog',
            index=models.Index(fields=['driver', 'ended_at'], name='driver_brea_driver__38a329_idx'),
        ),
    ]
