# Generated by Django 6.0.4 on 2026-09-02 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0028_wasterequest_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='zone',
            field=models.CharField(choices=[('north', 'North Zone'), ('south', 'South Zone'), ('east', 'East Zone'), ('west', 'West Zone'), ('central', 'Central Zone')], db_index=True, default='central', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='zone',
            field=models.CharField(choices=[('north', 'North Zone'), ('south', 'South Zone'), ('east', 'East Zone'), ('west', 'West Zone'), ('central', 'Central Zone')], db_index=True, default='central', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['zone', 'status'], name='bins_zone_7b5b21_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['zone', 'is_available'], name='drivers_zone_5ab257_idx'),
        ),
        migrations.AddIndex(
            model_name='wasterequest',
            index=models.Index(fields=['zone', 'status'], name='waste_reque_zone_a21793_idx'),
        ),
    ]
