# Generated by Django 5.2.17 on 2026-09-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0028_driverbreaklog_driver_break_reason_and_more'),
        ('api_app', '0029_bin_zone_driver_zone_bin_bins_zone_7b5b21_idx_and_more'),
    ]

    operations = [
    ]
