# Generated by Django 6.0.4 on 2026-09-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0030_merge_20260902_1301'),
        ('api_app', '0030_merge_20260902_1305'),
    ]

    operations = [
    ]
