# Generated by Django 6.0.4 on 2026-09-24 06:18

import api_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0031_merge_20260903_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/no_photo.png', help_text='Accepted formats: JPG, JPEG, PNG, GIF, WebP (Max 5MB)', null=True, upload_to='complaint_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), api_app.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='wasterequestphoto',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/no_photo.png', null=True, upload_to='waste_photos/extra/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), api_app.validators.validate_image_file]),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('partnership', 'Partnership / Business'), ('feedback', 'Feedback / Suggestion'), ('press', 'Press / Media'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='contact_mes_is_read_9f0758_idx'), models.Index(fields=['email', '-created_at'], name='contact_mes_email_edd3a9_idx')],
            },
        ),
    ]
