# Generated by Django 6.0.4 on 2026-09-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0032_alter_complaint_photo_alter_wasterequestphoto_photo_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='contact_mes_is_read_9f0758_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='contact_mes_email_edd3a9_idx',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
