# Generated by Django 6.0.4 on 2026-09-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0033_remove_contactmessage_contact_mes_is_read_9f0758_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='estimated_duration_min',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated route duration in minutes; computed when the route is generated.', null=True),
        ),
    ]
